#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FrontEnd.Resource", IsApplication=true)]

namespace FrontEnd
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::FrontEnd.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::FrontEnd.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::FrontEnd.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::FrontEnd.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::FrontEnd.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::FrontEnd.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::FrontEnd.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::FrontEnd.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::FrontEnd.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::FrontEnd.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::FrontEnd.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::FrontEnd.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::FrontEnd.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::FrontEnd.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::FrontEnd.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::FrontEnd.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::FrontEnd.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::FrontEnd.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::FrontEnd.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::FrontEnd.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::FrontEnd.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010039
			public const int MvxBind = 2130772025;
			
			// aapt resource value: 0x7f01003d
			public const int MvxDropDownItemTemplate = 2130772029;
			
			// aapt resource value: 0x7f01003e
			public const int MvxGroupItemTemplate = 2130772030;
			
			// aapt resource value: 0x7f01003c
			public const int MvxItemTemplate = 2130772028;
			
			// aapt resource value: 0x7f01003a
			public const int MvxLang = 2130772026;
			
			// aapt resource value: 0x7f01003f
			public const int MvxSource = 2130772031;
			
			// aapt resource value: 0x7f01003b
			public const int MvxTemplate = 2130772027;
			
			// aapt resource value: 0x7f010000
			public const int barrierAllowsGoneWidgets = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int barrierDirection = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int chainUseRtl = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int constraintSet = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int constraint_referenced_ids = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int content = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int emptyVisibility = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int layout_constrainedHeight = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int layout_constrainedWidth = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int layout_constraintBaseline_creator = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int layout_constraintBaseline_toBaselineOf = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int layout_constraintBottom_creator = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int layout_constraintBottom_toBottomOf = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int layout_constraintBottom_toTopOf = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int layout_constraintCircle = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int layout_constraintCircleAngle = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int layout_constraintCircleRadius = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int layout_constraintDimensionRatio = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int layout_constraintEnd_toEndOf = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int layout_constraintEnd_toStartOf = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int layout_constraintGuide_begin = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int layout_constraintGuide_end = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int layout_constraintGuide_percent = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int layout_constraintHeight_default = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int layout_constraintHeight_max = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int layout_constraintHeight_min = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int layout_constraintHeight_percent = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int layout_constraintHorizontal_bias = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int layout_constraintHorizontal_chainStyle = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int layout_constraintHorizontal_weight = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int layout_constraintLeft_creator = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int layout_constraintLeft_toLeftOf = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int layout_constraintLeft_toRightOf = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int layout_constraintRight_creator = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int layout_constraintRight_toLeftOf = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int layout_constraintRight_toRightOf = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int layout_constraintStart_toEndOf = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int layout_constraintStart_toStartOf = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int layout_constraintTop_creator = 2130772006;
			
			// aapt resource value: 0x7f010027
			public const int layout_constraintTop_toBottomOf = 2130772007;
			
			// aapt resource value: 0x7f010028
			public const int layout_constraintTop_toTopOf = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int layout_constraintVertical_bias = 2130772009;
			
			// aapt resource value: 0x7f01002a
			public const int layout_constraintVertical_chainStyle = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int layout_constraintVertical_weight = 2130772011;
			
			// aapt resource value: 0x7f01002c
			public const int layout_constraintWidth_default = 2130772012;
			
			// aapt resource value: 0x7f01002d
			public const int layout_constraintWidth_max = 2130772013;
			
			// aapt resource value: 0x7f01002e
			public const int layout_constraintWidth_min = 2130772014;
			
			// aapt resource value: 0x7f01002f
			public const int layout_constraintWidth_percent = 2130772015;
			
			// aapt resource value: 0x7f010030
			public const int layout_editor_absoluteX = 2130772016;
			
			// aapt resource value: 0x7f010031
			public const int layout_editor_absoluteY = 2130772017;
			
			// aapt resource value: 0x7f010032
			public const int layout_goneMarginBottom = 2130772018;
			
			// aapt resource value: 0x7f010033
			public const int layout_goneMarginEnd = 2130772019;
			
			// aapt resource value: 0x7f010034
			public const int layout_goneMarginLeft = 2130772020;
			
			// aapt resource value: 0x7f010035
			public const int layout_goneMarginRight = 2130772021;
			
			// aapt resource value: 0x7f010036
			public const int layout_goneMarginStart = 2130772022;
			
			// aapt resource value: 0x7f010037
			public const int layout_goneMarginTop = 2130772023;
			
			// aapt resource value: 0x7f010038
			public const int layout_optimizationLevel = 2130772024;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int box_edittext = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04003c
			public const int BornDayContainerID = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int BornDayLabelID = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int BornDayTextID = 2130968638;
			
			// aapt resource value: 0x7f040039
			public const int EmailContainerID = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int EmailLabelID = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int EmailTextID = 2130968635;
			
			// aapt resource value: 0x7f040042
			public const int GithubUsernameContainerID = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int GithubUsernameLabelID = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int GithubUsernameTextID = 2130968644;
			
			// aapt resource value: 0x7f040032
			public const int LevelContainerID = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int LevelLabelID = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int LevelTextID = 2130968628;
			
			// aapt resource value: 0x7f040000
			public const int MvvmCrossTagId = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindingTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040036
			public const int PhoneContainerID = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int PhoneLabelID = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int PhoneTextID = 2130968632;
			
			// aapt resource value: 0x7f04002f
			public const int PositionContainerID = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int PositionLabelID = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int PositionTextID = 2130968625;
			
			// aapt resource value: 0x7f040010
			public const int barrier = 2130968592;
			
			// aapt resource value: 0x7f040002
			public const int bottom = 2130968578;
			
			// aapt resource value: 0x7f040011
			public const int chains = 2130968593;
			
			// aapt resource value: 0x7f040035
			public const int contactDetailsTextID = 2130968629;
			
			// aapt resource value: 0x7f040012
			public const int dimensions = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int direct = 2130968595;
			
			// aapt resource value: 0x7f040003
			public const int end = 2130968579;
			
			// aapt resource value: 0x7f040029
			public const int firstNameContainerID = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int firstNameLabelID = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int firstnameTextID = 2130968619;
			
			// aapt resource value: 0x7f04003f
			public const int genderContainerID = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int genderLabelID = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int genderTextID = 2130968641;
			
			// aapt resource value: 0x7f040008
			public const int gone = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int invisible = 2130968585;
			
			// aapt resource value: 0x7f04002c
			public const int lastNameContainerID = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int lastNameLabelID = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int lastNameTextID = 2130968622;
			
			// aapt resource value: 0x7f040004
			public const int left = 2130968580;
			
			// aapt resource value: 0x7f040027
			public const int loginBtnID = 2130968615;
			
			// aapt resource value: 0x7f040025
			public const int loginNameTxtID = 2130968613;
			
			// aapt resource value: 0x7f040014
			public const int none = 2130968596;
			
			// aapt resource value: 0x7f04000e
			public const int packed = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int parent = 2130968586;
			
			// aapt resource value: 0x7f040026
			public const int passwordTxtID = 2130968614;
			
			// aapt resource value: 0x7f04000b
			public const int percent = 2130968587;
			
			// aapt resource value: 0x7f040005
			public const int right = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int spread = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int spread_inside = 2130968591;
			
			// aapt resource value: 0x7f040015
			public const int standard = 2130968597;
			
			// aapt resource value: 0x7f040006
			public const int start = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int top = 2130968583;
			
			// aapt resource value: 0x7f04001f
			public const int totalBorndaysContainerID = 2130968607;
			
			// aapt resource value: 0x7f04001b
			public const int totalDeveloperCountID = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int totalDeveloperLabelID = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int totalDevelopersContainerID = 2130968601;
			
			// aapt resource value: 0x7f040016
			public const int totalEmployeesContainerID = 2130968598;
			
			// aapt resource value: 0x7f040018
			public const int totalEmployeesCountID = 2130968600;
			
			// aapt resource value: 0x7f040017
			public const int totalEmployeesLabelID = 2130968599;
			
			// aapt resource value: 0x7f040021
			public const int totalMonthlyBorndaysTeamCountID = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int totalMonthlyBorndaysTeamLabelID = 2130968608;
			
			// aapt resource value: 0x7f040022
			public const int totalReviewsContainerID = 2130968610;
			
			// aapt resource value: 0x7f040024
			public const int totalReviewsTeamCountID = 2130968612;
			
			// aapt resource value: 0x7f040023
			public const int totalReviewsTeamLabelID = 2130968611;
			
			// aapt resource value: 0x7f04001c
			public const int totalSalesContainerID = 2130968604;
			
			// aapt resource value: 0x7f04001e
			public const int totalSalesTeamCountID = 2130968606;
			
			// aapt resource value: 0x7f04001d
			public const int totalSalesTeamLabelID = 2130968605;
			
			// aapt resource value: 0x7f040028
			public const int userDetailsTextID = 2130968616;
			
			// aapt resource value: 0x7f04000d
			public const int wrap = 2130968589;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dashboard_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int employee_collection_view = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int login_view = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int user_profile_view = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ConstraintLayout_Layout = new int[] {
					16842948,
					16843039,
					16843040,
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024};
			
			// aapt resource value: 2
			public const int ConstraintLayout_Layout_android_maxHeight = 2;
			
			// aapt resource value: 1
			public const int ConstraintLayout_Layout_android_maxWidth = 1;
			
			// aapt resource value: 4
			public const int ConstraintLayout_Layout_android_minHeight = 4;
			
			// aapt resource value: 3
			public const int ConstraintLayout_Layout_android_minWidth = 3;
			
			// aapt resource value: 0
			public const int ConstraintLayout_Layout_android_orientation = 0;
			
			// aapt resource value: 5
			public const int ConstraintLayout_Layout_barrierAllowsGoneWidgets = 5;
			
			// aapt resource value: 6
			public const int ConstraintLayout_Layout_barrierDirection = 6;
			
			// aapt resource value: 7
			public const int ConstraintLayout_Layout_chainUseRtl = 7;
			
			// aapt resource value: 8
			public const int ConstraintLayout_Layout_constraintSet = 8;
			
			// aapt resource value: 9
			public const int ConstraintLayout_Layout_constraint_referenced_ids = 9;
			
			// aapt resource value: 10
			public const int ConstraintLayout_Layout_layout_constrainedHeight = 10;
			
			// aapt resource value: 11
			public const int ConstraintLayout_Layout_layout_constrainedWidth = 11;
			
			// aapt resource value: 12
			public const int ConstraintLayout_Layout_layout_constraintBaseline_creator = 12;
			
			// aapt resource value: 13
			public const int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 13;
			
			// aapt resource value: 14
			public const int ConstraintLayout_Layout_layout_constraintBottom_creator = 14;
			
			// aapt resource value: 15
			public const int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 15;
			
			// aapt resource value: 16
			public const int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 16;
			
			// aapt resource value: 17
			public const int ConstraintLayout_Layout_layout_constraintCircle = 17;
			
			// aapt resource value: 18
			public const int ConstraintLayout_Layout_layout_constraintCircleAngle = 18;
			
			// aapt resource value: 19
			public const int ConstraintLayout_Layout_layout_constraintCircleRadius = 19;
			
			// aapt resource value: 20
			public const int ConstraintLayout_Layout_layout_constraintDimensionRatio = 20;
			
			// aapt resource value: 21
			public const int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 21;
			
			// aapt resource value: 22
			public const int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 22;
			
			// aapt resource value: 23
			public const int ConstraintLayout_Layout_layout_constraintGuide_begin = 23;
			
			// aapt resource value: 24
			public const int ConstraintLayout_Layout_layout_constraintGuide_end = 24;
			
			// aapt resource value: 25
			public const int ConstraintLayout_Layout_layout_constraintGuide_percent = 25;
			
			// aapt resource value: 26
			public const int ConstraintLayout_Layout_layout_constraintHeight_default = 26;
			
			// aapt resource value: 27
			public const int ConstraintLayout_Layout_layout_constraintHeight_max = 27;
			
			// aapt resource value: 28
			public const int ConstraintLayout_Layout_layout_constraintHeight_min = 28;
			
			// aapt resource value: 29
			public const int ConstraintLayout_Layout_layout_constraintHeight_percent = 29;
			
			// aapt resource value: 30
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 30;
			
			// aapt resource value: 31
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 31;
			
			// aapt resource value: 32
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 32;
			
			// aapt resource value: 33
			public const int ConstraintLayout_Layout_layout_constraintLeft_creator = 33;
			
			// aapt resource value: 34
			public const int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 34;
			
			// aapt resource value: 35
			public const int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 35;
			
			// aapt resource value: 36
			public const int ConstraintLayout_Layout_layout_constraintRight_creator = 36;
			
			// aapt resource value: 37
			public const int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 37;
			
			// aapt resource value: 38
			public const int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 38;
			
			// aapt resource value: 39
			public const int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 39;
			
			// aapt resource value: 40
			public const int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 40;
			
			// aapt resource value: 41
			public const int ConstraintLayout_Layout_layout_constraintTop_creator = 41;
			
			// aapt resource value: 42
			public const int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 42;
			
			// aapt resource value: 43
			public const int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 43;
			
			// aapt resource value: 44
			public const int ConstraintLayout_Layout_layout_constraintVertical_bias = 44;
			
			// aapt resource value: 45
			public const int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 45;
			
			// aapt resource value: 46
			public const int ConstraintLayout_Layout_layout_constraintVertical_weight = 46;
			
			// aapt resource value: 47
			public const int ConstraintLayout_Layout_layout_constraintWidth_default = 47;
			
			// aapt resource value: 48
			public const int ConstraintLayout_Layout_layout_constraintWidth_max = 48;
			
			// aapt resource value: 49
			public const int ConstraintLayout_Layout_layout_constraintWidth_min = 49;
			
			// aapt resource value: 50
			public const int ConstraintLayout_Layout_layout_constraintWidth_percent = 50;
			
			// aapt resource value: 51
			public const int ConstraintLayout_Layout_layout_editor_absoluteX = 51;
			
			// aapt resource value: 52
			public const int ConstraintLayout_Layout_layout_editor_absoluteY = 52;
			
			// aapt resource value: 53
			public const int ConstraintLayout_Layout_layout_goneMarginBottom = 53;
			
			// aapt resource value: 54
			public const int ConstraintLayout_Layout_layout_goneMarginEnd = 54;
			
			// aapt resource value: 55
			public const int ConstraintLayout_Layout_layout_goneMarginLeft = 55;
			
			// aapt resource value: 56
			public const int ConstraintLayout_Layout_layout_goneMarginRight = 56;
			
			// aapt resource value: 57
			public const int ConstraintLayout_Layout_layout_goneMarginStart = 57;
			
			// aapt resource value: 58
			public const int ConstraintLayout_Layout_layout_goneMarginTop = 58;
			
			// aapt resource value: 59
			public const int ConstraintLayout_Layout_layout_optimizationLevel = 59;
			
			public static int[] ConstraintLayout_placeholder = new int[] {
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int ConstraintLayout_placeholder_content = 0;
			
			// aapt resource value: 1
			public const int ConstraintLayout_placeholder_emptyVisibility = 1;
			
			public static int[] ConstraintSet = new int[] {
					16842948,
					16842960,
					16842972,
					16842996,
					16842997,
					16842999,
					16843000,
					16843001,
					16843002,
					16843551,
					16843552,
					16843553,
					16843554,
					16843555,
					16843556,
					16843557,
					16843558,
					16843559,
					16843560,
					16843701,
					16843702,
					16843770,
					16843840,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023};
			
			// aapt resource value: 9
			public const int ConstraintSet_android_alpha = 9;
			
			// aapt resource value: 22
			public const int ConstraintSet_android_elevation = 22;
			
			// aapt resource value: 1
			public const int ConstraintSet_android_id = 1;
			
			// aapt resource value: 4
			public const int ConstraintSet_android_layout_height = 4;
			
			// aapt resource value: 8
			public const int ConstraintSet_android_layout_marginBottom = 8;
			
			// aapt resource value: 20
			public const int ConstraintSet_android_layout_marginEnd = 20;
			
			// aapt resource value: 5
			public const int ConstraintSet_android_layout_marginLeft = 5;
			
			// aapt resource value: 7
			public const int ConstraintSet_android_layout_marginRight = 7;
			
			// aapt resource value: 19
			public const int ConstraintSet_android_layout_marginStart = 19;
			
			// aapt resource value: 6
			public const int ConstraintSet_android_layout_marginTop = 6;
			
			// aapt resource value: 3
			public const int ConstraintSet_android_layout_width = 3;
			
			// aapt resource value: 0
			public const int ConstraintSet_android_orientation = 0;
			
			// aapt resource value: 16
			public const int ConstraintSet_android_rotation = 16;
			
			// aapt resource value: 17
			public const int ConstraintSet_android_rotationX = 17;
			
			// aapt resource value: 18
			public const int ConstraintSet_android_rotationY = 18;
			
			// aapt resource value: 14
			public const int ConstraintSet_android_scaleX = 14;
			
			// aapt resource value: 15
			public const int ConstraintSet_android_scaleY = 15;
			
			// aapt resource value: 10
			public const int ConstraintSet_android_transformPivotX = 10;
			
			// aapt resource value: 11
			public const int ConstraintSet_android_transformPivotY = 11;
			
			// aapt resource value: 12
			public const int ConstraintSet_android_translationX = 12;
			
			// aapt resource value: 13
			public const int ConstraintSet_android_translationY = 13;
			
			// aapt resource value: 21
			public const int ConstraintSet_android_translationZ = 21;
			
			// aapt resource value: 2
			public const int ConstraintSet_android_visibility = 2;
			
			// aapt resource value: 23
			public const int ConstraintSet_layout_constrainedHeight = 23;
			
			// aapt resource value: 24
			public const int ConstraintSet_layout_constrainedWidth = 24;
			
			// aapt resource value: 25
			public const int ConstraintSet_layout_constraintBaseline_creator = 25;
			
			// aapt resource value: 26
			public const int ConstraintSet_layout_constraintBaseline_toBaselineOf = 26;
			
			// aapt resource value: 27
			public const int ConstraintSet_layout_constraintBottom_creator = 27;
			
			// aapt resource value: 28
			public const int ConstraintSet_layout_constraintBottom_toBottomOf = 28;
			
			// aapt resource value: 29
			public const int ConstraintSet_layout_constraintBottom_toTopOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintSet_layout_constraintCircle = 30;
			
			// aapt resource value: 31
			public const int ConstraintSet_layout_constraintCircleAngle = 31;
			
			// aapt resource value: 32
			public const int ConstraintSet_layout_constraintCircleRadius = 32;
			
			// aapt resource value: 33
			public const int ConstraintSet_layout_constraintDimensionRatio = 33;
			
			// aapt resource value: 34
			public const int ConstraintSet_layout_constraintEnd_toEndOf = 34;
			
			// aapt resource value: 35
			public const int ConstraintSet_layout_constraintEnd_toStartOf = 35;
			
			// aapt resource value: 36
			public const int ConstraintSet_layout_constraintGuide_begin = 36;
			
			// aapt resource value: 37
			public const int ConstraintSet_layout_constraintGuide_end = 37;
			
			// aapt resource value: 38
			public const int ConstraintSet_layout_constraintGuide_percent = 38;
			
			// aapt resource value: 39
			public const int ConstraintSet_layout_constraintHeight_default = 39;
			
			// aapt resource value: 40
			public const int ConstraintSet_layout_constraintHeight_max = 40;
			
			// aapt resource value: 41
			public const int ConstraintSet_layout_constraintHeight_min = 41;
			
			// aapt resource value: 42
			public const int ConstraintSet_layout_constraintHeight_percent = 42;
			
			// aapt resource value: 43
			public const int ConstraintSet_layout_constraintHorizontal_bias = 43;
			
			// aapt resource value: 44
			public const int ConstraintSet_layout_constraintHorizontal_chainStyle = 44;
			
			// aapt resource value: 45
			public const int ConstraintSet_layout_constraintHorizontal_weight = 45;
			
			// aapt resource value: 46
			public const int ConstraintSet_layout_constraintLeft_creator = 46;
			
			// aapt resource value: 47
			public const int ConstraintSet_layout_constraintLeft_toLeftOf = 47;
			
			// aapt resource value: 48
			public const int ConstraintSet_layout_constraintLeft_toRightOf = 48;
			
			// aapt resource value: 49
			public const int ConstraintSet_layout_constraintRight_creator = 49;
			
			// aapt resource value: 50
			public const int ConstraintSet_layout_constraintRight_toLeftOf = 50;
			
			// aapt resource value: 51
			public const int ConstraintSet_layout_constraintRight_toRightOf = 51;
			
			// aapt resource value: 52
			public const int ConstraintSet_layout_constraintStart_toEndOf = 52;
			
			// aapt resource value: 53
			public const int ConstraintSet_layout_constraintStart_toStartOf = 53;
			
			// aapt resource value: 54
			public const int ConstraintSet_layout_constraintTop_creator = 54;
			
			// aapt resource value: 55
			public const int ConstraintSet_layout_constraintTop_toBottomOf = 55;
			
			// aapt resource value: 56
			public const int ConstraintSet_layout_constraintTop_toTopOf = 56;
			
			// aapt resource value: 57
			public const int ConstraintSet_layout_constraintVertical_bias = 57;
			
			// aapt resource value: 58
			public const int ConstraintSet_layout_constraintVertical_chainStyle = 58;
			
			// aapt resource value: 59
			public const int ConstraintSet_layout_constraintVertical_weight = 59;
			
			// aapt resource value: 60
			public const int ConstraintSet_layout_constraintWidth_default = 60;
			
			// aapt resource value: 61
			public const int ConstraintSet_layout_constraintWidth_max = 61;
			
			// aapt resource value: 62
			public const int ConstraintSet_layout_constraintWidth_min = 62;
			
			// aapt resource value: 63
			public const int ConstraintSet_layout_constraintWidth_percent = 63;
			
			// aapt resource value: 64
			public const int ConstraintSet_layout_editor_absoluteX = 64;
			
			// aapt resource value: 65
			public const int ConstraintSet_layout_editor_absoluteY = 65;
			
			// aapt resource value: 66
			public const int ConstraintSet_layout_goneMarginBottom = 66;
			
			// aapt resource value: 67
			public const int ConstraintSet_layout_goneMarginEnd = 67;
			
			// aapt resource value: 68
			public const int ConstraintSet_layout_goneMarginLeft = 68;
			
			// aapt resource value: 69
			public const int ConstraintSet_layout_goneMarginRight = 69;
			
			// aapt resource value: 70
			public const int ConstraintSet_layout_goneMarginStart = 70;
			
			// aapt resource value: 71
			public const int ConstraintSet_layout_goneMarginTop = 71;
			
			public static int[] LinearConstraintLayout = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int LinearConstraintLayout_android_orientation = 0;
			
			public static int[] MvxBinding = new int[] {
					2130772025,
					2130772026};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130772027};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130772030};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130772031};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130772028,
					2130772029};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
